version: '3'
services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "5001:5001"
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mongo
    ports:
      - "27018:27017"

        
       
